# Dockerfile
# ----------
# Builds the newsgroups semantic search service.
#
# Multi-stage approach: we use a slim Python base to keep the image small.
# The sentence-transformers model is downloaded at container startup (first run),
# so the image stays lean. Alternatively, bake it in by adding a download step.

FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Install system dependencies for chromadb (sqlite3, etc.)
RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    && rm -rf /var/lib/apt/lists/*

# Copy and install Python dependencies first (layer caching)
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY *.py ./

# Copy pre-built embeddings and cluster model (generated by setup.py)
# If these don't exist locally, run `python setup.py` first, then build the image.
COPY embeddings/ ./embeddings/

# Expose the service port
EXPOSE 8000

# Health check — hits the root endpoint every 30s
HEALTHCHECK --interval=30s --timeout=10s --start-period=60s \
    CMD curl -f http://localhost:8000/ || exit 1

# Start the uvicorn server
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
